### PR TITLE
Object Actions in functions, some Fixes and Ticket-Based Spawn System

### PR DESCRIPTION
**Pull request by Vehementis**
- increase z to prevent false intersection with the ground
- Fixed: exploding bulwarkBox
- Moved BuildObject actions into separate Functions
- Ticket-Based Respawn System

### CODE REVIEW

**Comment by Omnomios** [comment]
Love the refactor. Some good work in this pull request. I really like some of the bugfixes but it's mixed in with design changes that will need to be discussed with @thatParadox before I can merge them in.

My two concerns; 
1. Allowing players to sell objects changes the design.
2. What is your motivation behind adding the ticket base spawning? The perma-death during rounds is a core design choice that increases the cost of death and forces more conservative play. Messing with this possibly will make for a more run-and-gun mission.

That said, more choices are always better and as long as it can be turned of in the parameters then there's really no harm including it.

We'll need to run it by @thatParadox before I merge this in.

**Comment by thatParadox** [comment]
Nice work! Yeah, I think tickets would work as long as they are a parameter and by default it's infinite. Then if people want to up the difficulty they can limit the number of re-spawns they can have.

What's the change for Respawn time? Does that allow them to respawn during the wave? If so, I don't think I want that as part of the mission.

**Comment by thatParadox** [comment]
Oh, but no to being able to sell back the stuff you put down. We don't want people selling stuff other players have placed and even then we want choice to be permanent. No refunds. Also I like the current colours.

**Comment by Vehementis** [comment]
yeap well I was trying to contact you before but didn't get any response on steam so I just did this pull request.
to disable the sell Option you just have to comment out line 8 in de fn_sell.sqf and change the Option text in the purchase.sqf
The respawn system was added because I and some other ppl wanted to be able to play it Singleplayer.
these tickets are pure for respawn in Wave so you don't loose instant if you die once. the respawn between waves doesn't count on the tickets. so if you want the game to be like it is now just set de default tickets to 0 (that's why I added it as an option).
I didn't mean to change the colours, I got those from the last version, ill adjust that.
ill also disable the unwanted functions and do another commit.

**Comment by Vehementis** [comment]
ok, I changed the Sell action back to Remove and disabled the refound.
I think there was just one Color that I got wrong while putting it into functions, adjusted it.
I did set the Default value for the respawn tickets to 0.

The respawn system was my main reason why I started to edit this mission.
I mainly play singleplayer and without any teammates to revive you the game is over quite fast.
So I added a respawn system, so I can respawn during the waves.
The forced respawns between waves doesn't count on the Tickets.
So if you set the Tickets to 0 there will be no respawns during wave and the free Respawns between waves won't be affected.

You still will lose all your equipment (if you get revived by a teammate you won't), so the cost of death is still higher then in Multiplayer. But you will get a 2nd chance to get back into the game.

**Comment by Omnomios** [comment]
I'm good to merge this in. We'll need to do some play testing to see how it flows though.

"I was trying to contact you before but didn't get any response on steam" I didn't realize, sorry. The comments section is a bit chaotic.

**Comment by Vehementis** [comment]
I also did send a friend request to hilltop one day before writing to the comments, but its ok, I also don't respond to everything I get on steam.

**Pull request merged**
